### ISSUE TITLE
Memory restriction for Symbol Server containers

### ISSUE THREAD

**Issue by realgarp** [nemtech/symbol-bootstrap#100]
When running and testing different versions and setups of the catapult and Symbol server, issues of memory consumption frequently arose. In the symbol network a big difference in setups and sizes of servers is to be expected and probably even preferable. 

During the Symbol testnet phase an attempt was made to limit the memory used by the server with the suggestion to use the mem_limit option in the .yml file to restrict the memory consumption of the mongo db.
However, even when using that option, memory issues kept occurring and occasionally even crashed other processes running on the server. That should never occur.

In order to limit the used memory or to manage or tune it, I would like to submit a feature request formulated before: 
Could symbol-bootstrap support a total memory limit for all symbol server docker containers together? 
And not just use a memory limit for one of its components, such as the mem_limit option for the mongo db. 
I hope such feature is feasible and can be added to the symbol-bootstrap tool with minor changes to the frozen Symbol code.
Such a memory limit would certainly be an added value for node owner's at the time of Symbol launch, specifically for supernode owners to allow them to configure a very stable environment.

**Comment by fboucquez** [comment]
Hi @realgarp , thank you for raising this issue.

There is a known issue about catapult server's memory usage. 

https://github.com/nemtech/catapult-server/issues/133

I would wait for this one to be resolved before defining a hardcoded/calculated default in Bootstrap. The only one calculated is the mongo memory limit as it was a recurring issue.

Having said that, you can tune how the docker-compose.yml file is created with presets. 

https://github.com/nemtech/symbol-bootstrap/blob/main/docs/presetGuides.md#add-docker-compose-properties-to-services

So you can set 
````
nodes:
    - compose:
          cpu_count: 3
          mem_limit: '1024m'
    - brokerCompose:
          mem_limit: '{{computerMemory 25}}' // 25 % max limit
gateways:
    - compose:
          mem_limit: '2048m'
````

Please try different memory limits and let us know how your tests go.

**Comment by realgarp** [comment]
I have tried to run different memory configurations on the testnet. 
Until now i could not find any configuration where the symbol server could run with 8GB RAM. And that's already a medium sized VPS or VM. 
Symbol always gets into trouble with memory and crashes. In the worst cases, it even crashed other processes running on the VM as earlier indicated. In one situation there was not enough memory left to run "symbol-bootstrap stop". And in the most catastrophic situation I could not even login remotely and get to the command line because there was probably no memory left for ssh. I had to login the the VPS provider and restart the server from there.

**Comment by fboucquez** [comment]
Thanks @realgarp for your input. The team is working on the memory issue.

**Comment by fboucquez** [comment]
@Wayonb , is this still an issue?

**Comment by fboucquez** [comment]
Closing. Server memory issue have been fixed.
