### ISSUE TITLE
0.3.2-alpha-202012300211 may be hardware dependent

### ISSUE THREAD

**Issue by dusanjp** [nemtech/symbol-bootstrap#101]
I've done this "0.3.2-alpha-202012300211" in a different hardware environment and found that some work and some don't. I think it's a hardware issue.
Perhaps it's about CPU extension instructions
May be similar to the previous "avx2" issue
It doesn't seem to be related to the installed software version

**Comment by fboucquez** [comment]
Can you describe the environment and the issue you are having? Any error, exception in the logs?

**Comment by dusanjp** [comment]
t4vps c8/c16/c24
All of these failed to launch Alpha

my environment
Below is the "t4vps c8 plan" spec for one of them

Software version used
node v14.15.3
npm 6.14.9
docker Docker version 20.10.1, build 831ebea
docker-compose version 1.28.0-rc1, build 1f469474
symbol-bootstrap/0.3.2-alpha-202012300211 linux-x64 node-v10.19.0
ubuntu20.04/18.04/16.04 (I tried these three versions)

hardware
cpu Intel(R) Xeon(R) CPU E5-2640 v4 @ 2x2.40GHz
Memory: 8192 MB
Hard disk: 80 GB 

The following is the operating procedure
rm -rf target
docker system prune -a
symbol-bootstrap config -p testnet -a dual -c custom.yml
symbol-bootstrap compose
symbol-bootstrap run -d

I got an error like this when starting the DB
Creating db         ... error
ERROR: for db  Cannot start service db: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:326: applying cgroup configuration for process caused: failed to set memory.kmem.limit_in_bytes,

ERROR: for db  Cannot start service db: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:326: applying cgroup configuration for process caused: failed to set memory.kmem.limit_in_bytes, because either tasks have already joined this cgroup or it has children: unknown
Encountered errors while bringing up the project.
Process exited with code 1 and signal null
Process closed with code 1

There is also the fact that others using "t4vps c8" have successfully started, but in my above environment they all give the same errer

I have confirmed success with the "same operation method" in two other environments that I own separately.

**Comment by fboucquez** [comment]
Thanks @dusanjp 

If you remove the mem_limit field from ./target/docker/docker-compose.yml, can your server restart?

**Comment by dusanjp** [comment]
Yes Can be started normally without "mem_limit"
After that, I tried docker-compose ver. From 1.26.0 to 1.28.0-rc1 respectively.
After all, with "mem_limit", DB startup fails with the same error.

**Comment by fboucquez** [comment]
Hi @dusanjp , could you try this fix in your environment? Please install the latest bootstrap alpha

https://github.com/nemtech/symbol-bootstrap/issues/109#issuecomment-755351029

**Comment by dusanjp** [comment]
I tryed 'symbol-bootstrap/0.3.2-alpha-202101052048' with docker-compose 1.26.0/1.27.4

Creating api-broker ...
Creating db         ... error

ERROR: for db  Cannot start service db: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:326: applying cgrCreating api-broker ... done
because either tasks have already joined this cgroup or it has children: unknown

Creating api-node   ... done

ERROR: for db  Cannot start service db: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:326: applying cgroup configuration for process caused: failed to set memory.kmem.limit_in_bytes, because either tasks have already joined this cgroup or it has children: unknown
Encountered errors while bringing up the project.
Process exited with code 1 and signal null
Process closed with code 1

umm...

**Comment by fboucquez** [comment]
It seems like the error is the one from the preview test...

have you tried the following preset?
````
databases:
    - compose:
          mem_limit: ~ //Removes the nem_limit from the default preset
          command: 'mongod --dbpath=/dbdata --bind_ip=db --wiredTigerCacheSizeGB 2'
````

**Comment by dusanjp** [comment]
nodes:
    -
        host: 212.24.106.178
        friendlyName: test8
        ##voting: true
        beneficiaryAddress:
        mainPrivateKey:
        transportPrivateKey:
        remotePrivateKey:
        votingPrivateKey:
        vrfPrivateKey:

databases:
    - compose:
              mem_limit: ~ //Removes the nem_limit from the default preset
                        command: 'mongod --dbpath=/dbdata --bind_ip=db --wiredTigerCacheSizeGB 2'

i wii try this customfile

**Comment by dusanjp** [comment]
once tryed

docker.errors.DockerException: The specified value for memory (~ //Removes the nem_limit from the default preset) should specify
 the units. The postfix should be one of the `b` `k` `m` `g` characters
Process exited with code 255 and signal null
Process closed with code 255

**Comment by fboucquez** [comment]
uff, please remove what's after the //comment (just keep ~)

**Comment by dusanjp** [comment]
I see w
I'll try

**Comment by dusanjp** [comment]
symbol-bootstrap/0.3.2-alpha-202101052048
with that profile

It works ...
db is working!

**Comment by fboucquez** [comment]
Cool, thanks @dusanjp. It's highly possible we move that preset to default so you don't need to provide those params anymore

**Comment by dusanjp** [comment]
Thank you
I have a question, is memory limitation enabled in this state?

**Comment by fboucquez** [comment]
In theory yes, it's limited by mongo instead of docker (that you have the problem with mem_limit). We are still doing testing

**Comment by fboucquez** [comment]
We are removing the default mongo mem_limit in favor of wiredTigerCacheSizeGB

https://github.com/nemtech/symbol-bootstrap/pull/111

Closing this. Thanks @dusanjp
