### ISSUE TITLE
Improve the recovery on the api node.

### ISSUE THREAD

**Issue by Wayonb** [nemtech/symbol-bootstrap#108]
**Describe the bug**
Currently, if the broker dies and recovery is run without the API node getting shutdown, it can lead to an issue with the DB.

**To Reproduce**
To reproduce the behavior:
kill the broker while the API node is running.

**Expected behavior**
if either the broker or API node crashes, both nodes need to stop then run the recovery tool before restarting.

**Comment by fboucquez** [comment]
I don't know a way of doing this without merging broker and server in the same compose box.

**Comment by fboucquez** [comment]
Fixed in dev
