### ISSUE TITLE
link -unlink does not complete (It takes too long)

### ISSUE THREAD

**Issue by dusanjp** [nemtech/symbol-bootstrap#126]
link --unlink does not complete

When I ran link --unlink now, almost 1 hour has passed without the processing being completed.
Is this behavior proper?

main account:
TD7TGL-KPMNF2-XDGYW3-ZNQAHR-6TIJS4-2IGF6A-WYA
remote account:
TBYVTV-ZXWDD5-Q7BU4O-GJKTQS-Y2OBSZ-NX5WFT-72I

Executed node:
119.47.17.86
nodename:
PASOMI3++ RYZEN5 2400G

There is a report that the same phenomenon occurred in another unlink that was done at about the same time.

![image](https://user-images.githubusercontent.com/62555389/105572251-691fc000-5d99-11eb-829f-82208be4d09d.png)

**Comment by dusanjp** [comment]
Postscript

After about an hour and a half
--unlink passed
However
Isn't this operation slow?
I think it's rare, but .....
![image](https://user-images.githubusercontent.com/62555389/105572458-9caf1a00-5d9a-11eb-8f1d-8e01f6e7c4e5.png)

**Comment by fboucquez** [comment]
Hi @dusanjp . Could you try the  --maxFee?

Closing this issue. An improvement to the default max fee has been logged into the other issue.
