### ISSUE TITLE
Link command's transaction fee should refer to `/network/fees/transaction`

### ISSUE THREAD

**Issue by daoka** [nemtech/symbol-bootstrap#127]
Link command's transactions maximum fee is fixed at 0.1.
If the network is busy, these transactions take time to confirm or become invalid when the deadline is reached.

So, the link command's transactions maximum fee should refer to `https://localhost:3000/network/fees/transaction`, and set this response (averageFeeMultiplier or medianFeeMultiplier)

**Comment by daoka** [comment]
I think #126 is related to this issue.

**Comment by fboucquez** [comment]
Thanks. I'll make the default max fee dynamic. For now can you use the --maxFee?

https://github.com/nemtech/symbol-bootstrap/blob/main/docs/link.md

**Comment by daoka** [comment]
Thank you.
I can use the --maxFee option, it works.

**Comment by fboucquez** [comment]
Boostrap uses the node's minFeeMultiplier by default on v 0.4.2
