### ISSUE TITLE
Synchronization slowed down after changing the transactionSelectionStrategy.

### ISSUE THREAD

**Issue by GodTanu** [nemtech/symbol-bootstrap#130]
symbol-bootstrap/0.4.1 linux-x64 node-v14.15.4
Docker version 20.10.2, build 2291f61
Node v14.15.4

Synchronization slowed down after changing the transactionSelectionStrategy.
HealthCheck results are fine.

After changing the settings of the `transactionSelectionStrategy(config-node.properties)`, the synchronization gradually started to lag. After some time, it delays even more.

The phenomenon occurs when the setting value is changed to `oldest` & `minimize-fee`.

![image](https://user-images.githubusercontent.com/20492223/106103517-6b609080-6184-11eb-8bce-888697acee02.png)

![image](https://user-images.githubusercontent.com/20492223/106103629-95b24e00-6184-11eb-9b90-cffba62bd6cc.png)

**Comment by fboucquez** [comment]
Is this a bootstrap or a server issue? @Wayonb

**Comment by Jaguar0625** [comment]
Did you restart after saving changes?

**Comment by gimer** [comment]
that sounds like coincidence / some other variables.
transactionSelectionStrategy affects only harvesting, and out of 3 options, both `oldest` and `minimize-fee` are actually both faster than `maximize-fee` (so if anything, they should result in speedup rather than slow down)

**Comment by GodTanu** [comment]
Thank you for answer.

@Jaguar0625 
After the changes were made, a reboot was performed.
When the problem occurred, finalization stalled at 56880.

@gimer 
Then I changed the setting back to maximize-fee and did the sync, but it stalled at 56880.
It may be an accidental phenomenon.

I will monitor it some more.
In any case, I feel it would be better to set the bootstrap default to 'ordoest'.

**Comment by GodTanu** [comment]
Now that the synchronization is complete, monitor it again.
The settings have been changed to minimize.
If there are any abnormalities, I will report again. If there is no problem, close it.
![image](https://user-images.githubusercontent.com/20492223/106217742-40744c00-6219-11eb-8d0e-f44dfa8f66d6.png)

**Comment by fboucquez** [comment]
Thanks!
