### ISSUE TITLE
Various harvesting stopped after ResetData

### ISSUE THREAD

**Issue by GodTanu** [nemtech/symbol-bootstrap#145]
I was doing remote harvesting. Remote harvesting was working.
The acceptance of delegated harvesting was also done correctly.

After the node went down during the stress test, I stopped the node and ran "Bootstrap ResetData".
Again, the synchronization was completed and the node is now working fine.

But it appears that all harvesting has not resumed.

Looking at the return of "http://localhost:3000/node/unlockedaccount", only the public key for the main account for remote harvesting was set.

I felt something was wrong, so I checked the data and found that "harvesters.dat" had been deleted.
As a result, harvesting of accounts with delegated harvesting has also been suspended.

I have a question.

1.Why has remote harvesting stopped?
2.Is it correct that "Harvesters.dat" is deleted by "Bootstrap ResetData"?
3.If I back up the "harvesters.dat" data, will it restart automatically?

**Comment by GodTanu** [comment]
Supplemental. 
my setup is
`delegatePrioritizationPolicy = Age`

**Comment by GodTanu** [comment]
After the resync after ResetData, the remote harvesting on my node had stopped.
Today, I stopped the node (symbol-bootstrap stop).
Next, I restarted it (symbol-bootstrap start).
Then, the harvesting worked.

If the resync is complete, do I have to reboot the node to resume harvesting?

![image](https://user-images.githubusercontent.com/20492223/107721920-34ac7d80-6d21-11eb-8786-cfd69d55a0b7.png)

**Comment by dusanjp** [comment]
(Additional supplement)

Currently among us
When node is restarted (rebuild / resetData)
As a way to resume harvesting
After synchronization, I have taken the procedure of (stop / run) node once. Is this the correct specification?

**Comment by gimer** [comment]
Assuming you have same certificates as before, harvesters.dat should be recovered during re-sync

**Comment by Jaguar0625** [comment]
@GodTanu do you happen to have saved logs during this test?

**Comment by GodTanu** [comment]
Sorry for the late reply.
I think the log is lost because I already did a STOP/START. The target node is still running, so If you want this log,  please teach me know how to collect log.

As we discussed on NEM2Slack.
I think the problem with delegated harvesting not resuming was due to the fact that I had not backed up "Harvesters.dat".
I'm hoping that if possible, "Harvesters.dat" will be backed up automatically during ResetData

The problem this time was that remote harvesting was not resumed.

**Comment by GodTanu** [comment]
See here for problems preventing the resumption of remote harvesting.
https://github.com/nemtech/catapult-server/issues/158

**Comment by dusanjp** [comment]
Until now, after synchronization was completed, local harvesting was restarted with stop / run of node.
In v0.4.3, I confirmed that it starts automatically without the above operation.
I'm checking this with multiple nodes I have
I admit that it has improved

**Comment by fboucquez** [comment]
Thanks for the info @dusanjp , are you happy about closing this issue?

**Comment by GodTanu** [comment]
I think it is good to close. But...
How do I fix the problem of "Harvesters.dat" disappearing in ResetData?
Is this a specification?
Isn't there something I should do to improve it?

**Comment by fboucquez** [comment]
I believe I have replicated the issue. Raised a server bug in https://github.com/nemtech/catapult-server/issues/173

**Comment by fboucquez** [comment]
Server with a fix has been released in bootstrap 1.0.6.
