### ISSUE TITLE
errors when trying to update the node

### ISSUE THREAD

**Issue by myxmaster** [nemtech/symbol-bootstrap#153]
**Describe the bug**
After updating symbol-bootstrap and restarting the node with --upgrade parameter, I see this:
![grafik](https://user-images.githubusercontent.com/77545287/108001358-84729980-6fec-11eb-8a8e-00010947dced.png)

Tried all this, but doesn't help:
- Rebooting the VPS
- `symbol-bootstrap config -p testnet -a dual --upgrade -c enable-voting-preset.yml`
- `symbol-bootstrap compose`

**To Reproduce**
To reproduce the behavior:
1. `symbol-bootstrap stop`
2. `npm install -g symbol-bootstrap`
3. `symbol-bootstrap start -p testnet -a dual --upgrade -c enable-voting-preset.yml`

enable-voting-preset.yml:
```
nodes:
- voting: true

```

**Logs**
Please tell me if you need any other logs and how/where to get those.
[logs-20210216.zip](https://github.com/nemtech/symbol-bootstrap/files/5984661/logs-20210216.zip)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.2 LTS
 - symbol-bootstrap/0.4.3 linux-x64 node-v10.19.0
 - Docker version 19.03.8, build afacb8b7f0
 - Node Version ? (where do I see this?)

**Additional context**
I noticed something is wrong with docker. It didn't react at all (`docker -v` or `docker ps`... I had to CTRL+C), so I did `docker system prune -a` and after that it is responding again, but the problem with starting the node (screenshot above) stays.

**Comment by myxmaster** [comment]
In case it helps:

addresses.yml:
![grafik](https://user-images.githubusercontent.com/77545287/108040454-9af51100-703d-11eb-9a25-d6df90736e94.png)

**Comment by fboucquez** [comment]
Why there is no main account in addresses.yml? Did you manually remove it from the file?

**Comment by myxmaster** [comment]
yes, i don't want the private key of an account with funds on a VPS of course...

**Comment by myxmaster** [comment]
Was it wrong to delete the main account from addresses.yml?
If so, why does the node start and function normally, but only updates are not possible?

**Comment by fboucquez** [comment]
Atm, the main account private key needs to be provided to generate the server ca certificate, redone on the --upgrade.
To mitigate this we are adding encrypt/decrypt commands to bootstrap. When required, bootstrap will ask for the password to decrypt the custom preset, preset.yml and addresses.yml.

https://github.com/nemtech/symbol-bootstrap/pull/160

**Comment by fboucquez** [comment]
Hi @myxmaster , 

I've added privateKeySecurityMode to Bootstrap. I think it will address some of your security concerns around the main private keys.

Please have a look at the docs https://github.com/nemtech/symbol-bootstrap/blob/dev/docs/presetGuides.md#private-keys-and-security.  You can try it out by installing bootstrap 0.4.5-alpha-202103011623

You may want to use this setup:

https://github.com/nemtech/symbol-bootstrap/blob/dev/docs/presetGuides.md#never-stored-main-private-key

**Comment by fboucquez** [comment]
fixed in dev with the private key security modes
