### ISSUE TITLE
Unhandled exception when testing node/health during healthCheck

### ISSUE THREAD

**Issue by meyns** [nemtech/symbol-bootstrap#176]
Trying to run the healthCheck but apparently REST was not running fine yet and I got this exception:

2021-03-01T20:55:21.627Z info     Testing http://localhost:3000/node/health
(node:3362394) UnhandledPromiseRejectionWarning: #<Response>
(node:3362394) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:3362394) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2021-03-01T20:55:21.643Z warn     Rest http://localhost:3000/node/health is NOT up and running YET: {"statusCode":503,"statusMessage":"Service Unavailable","body":"{\"status\":{\"apiNode\":\"down\",\"db\":\"up\"}}"}

**Comment by fboucquez** [comment]
The health check should fail because Rest wasn't running. Is this happening?

The UnhandledPromiseRejectionWarning warning should be there.

**Comment by meyns** [comment]
The rest was not running ok, but imo the unhandled exception should be handled much cleaner. Especially if it is deprecated.
