### ISSUE TITLE
Local node should not be added to peers files.

### ISSUE THREAD

**Issue by Wayonb** [nemtech/symbol-bootstrap#182]
**Describe the bug**
When the peers file is generated the local node should not be added

**Comment by Wayonb** [comment]
Example of what gets added for testnet nodes

    {
      "publicKey": "1650124BE4392427B52AE85AF1D45967D951BB3D413A3FF85BC5AC6263A1F015",
      "endpoint": {
        "host": "",
        "port": 7900
      },
      "metadata": {
        "roles": "Peer,Api"
      }
    },

**Comment by fboucquez** [comment]
At all or only when there is no hostname/ip?

What about private networks? Each peer should be excluded from its own list? 
A network with peers A, B, C, 
A list should B,C, 
B list should have A, C, etc?

**Comment by fboucquez** [comment]
Do we need peer files on the broker config folder?
