### ISSUE TITLE
Unconfirmed transaction after link command

### ISSUE THREAD

**Issue by meyns** [nemtech/symbol-bootstrap#195]
After sending a symbol-bootstrap link command I get an unconfirmed transaction that doesn't get confirmed. It is a 2of2 multisig transaction with 3 cosigners
This is the unconfirmed transaction: http://explorer.symbolblockchain.io/transactions/3647196E71BD2885DF0FE15E682D5172C818567C3729F8C72C36180FD82A337E
Trying again with higher fee (--maxFee 1000000) gets me this error:
Failure_AccountLink_Remote_Account_Ineligible

**Comment by fboucquez** [comment]
Failure_AccountLink_Remote_Account_Ineligible means that the remote account cannot be linked to the main account.

http://explorer.symbolblockchain.io/transactions/3647196E71BD2885DF0FE15E682D5172C818567C3729F8C72C36180FD82A337E took longer than expected? is all fully linked now?

**Comment by fboucquez** [comment]
Closing this issue, please re open if you are still have an issue
