### ISSUE TITLE
Permission denied running docker images as user

### ISSUE THREAD

**Issue by fboucquez** [nemtech/symbol-bootstrap#20]
Bootstrap tries to run images as current user by default. This is to avoid docker creating folders and files in volumes as root which is not recommended. 

In some environments, running the bootstrap images when creating certificates or nemgen fails with permission denied. 

```
symbolplatform/symbol-server:tools-gcc-0.9.6.4 bash -c cd /data && bash createCertificate.sh
    Error: Command failed: docker run --rm -u 1000:1000 -v /home/vagrant/target/config/api-node/resources/cert:/data:rw symbolplatform/symbol-server:tools-gcc-0.9.6.4 "bash" "-c" "cd 
    /data && bash createCertificate.sh"
    docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/containers/create: dial 
    unix /var/run/docker.sock: connect: permission denied.
    See 'docker run --help'.
    Code: 126
```
In some cases, when running with sudo, some users get:

```
2020-09-20T11:49:57.391Z info [SYSTEM_LOG]     Running image using Exec: symbolplatform/symbol-server:tools-gcc-0.9.6.4 bash -c cd /data && bash createCertificate.sh
    Error: Command failed: docker run --rm -u 0:0 -v /home/vagrant/target/config/api-node/resources/cert:/data:rw 
    symbolplatform/symbol-server:tools-gcc-0.9.6.4 "bash" "-c" "cd /data && bash createCertificate.sh"
    mkdir: cannot create directory 'new_certs': Permission denied
    touch: cannot touch 'index.txt.attr': Permission denied
    Code: 1
```

In this case: `echo $(id -u):$(id -g)` returns `0:0`

Certificate and Nemgen creation has been improved in [0.10.0.1 branch](https://github.com/nemtech/symbol-bootstrap/pull/15) . In that branch, not providing a user is possible but the files are created using root. 

This task is to try to replicate the problem locally and to try a good combination of `user:group` that creates the files as the local user.

https://vsupalov.com/docker-shared-permissions/

Reported by @44uk

**Comment by fboucquez** [comment]
@44uk can I close this one? 

Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/containers/create: dial 
    unix /var/run/docker.sock: connect: permission denied.

Can be fixed by allowing docker to run without sudo. We have added the guide to fix this. Nothing else to do.

**Comment by 44uk** [comment]
After updated latest version, I don't met these problems. It seems to be good. Thanks!
