### ISSUE TITLE
Improve custom preset types

### ISSUE THREAD

**Issue by fboucquez** [nemtech/symbol-bootstrap#200]
use DeepPartial<PresetData> instead of any

Like:
https://github.com/nemtech/symbol-bootstrap/blob/15ef48353fd7629190a0e9d6792501412bfb58da/src/commands/wizard.ts#L80

Move to lib apis.

**Comment by tomokikato8** [comment]
In which file do I configure my own domain name?

**Comment by fboucquez** [comment]
https://github.com/nemtech/symbol-bootstrap/blob/main/docs/presetGuides.md#custom-nodes-friendly-names-and-hosts
