### ISSUE TITLE
Illegal instruction start.sh

### ISSUE THREAD

**Issue by dekm** [nemtech/symbol-bootstrap#207]
**Describe the bug**
When attempting to start a new node I receive the following error.

**To Reproduce**
```
symbol-bootstrap start -p mainnet -a peer
```
This is the error output.

```
Attaching to node
node    | RUNNING server NORMAL node
node    | !!!! Starting server....
node    | /symbol-commands/start.sh: line 126:    10 Illegal instruction     (core dumped) $catapultAppFolder/bin/$processName "$config"

```

**Expected behavior**
Node starts and syncs

Illegal instruction makes me think the source is compiled for never CPUs only.

**Desktop (please complete the following information):**
Ubuntu 18.04
CPU supports x86-64-v2

**Comment by Wayonb** [comment]
@dekm Can you provide more information on your CPU?
Currently, the server image requires ``skylake (2015) SSE4.2, AVX2``

**Comment by dekm** [comment]
> @dekm Can you provide more information on your CPU?
> Currently, the server image requires `skylake (2015) SSE4.2, AVX2`

It's a dual ``` Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz ``` server

```
  [Created at cpu.465]
  Unique ID: Jk7M.j8NaKXDZtZ6
  Hardware Class: cpu
  Arch: X86-64
  Vendor: "GenuineIntel"
  Model: 6.44.2 "Intel(R) Xeon(R) CPU           X5670  @ 2.93GHz"
  Features: fpu,vme,de,pse,tsc,msr,pae,mce,cx8,apic,sep,mtrr,pge,mca,cmov,pat,pse36,clflush,dts,acpi,mmx,fxsr,sse,sse2,ht,tm,pbe,syscall,nx,pdpe1gb,rdtscp,lm,constant_tsc,arch_perfmon,pebs,bts,rep_good,nopl,xtopology,nonstop_tsc,cpuid,aperfmperf,pni,pclmulqdq,dtes64,monitor,ds_cpl,vmx,smx,est,tm2,ssse3,cx16,xtpr,pdcm,pcid,dca,sse4_1,sse4_2,popcnt,aes,lahf_lm,pti,ssbd,ibrs,ibpb,stibp,tpr_shadow,vnmi,flexpriority,ept,vpid,dtherm,ida,arat,flush_l1d
  Clock: 1600 MHz
  BogoMips: 4800.52
  Cache: 12288 kb
  Units/Processor: 32
  Config Status: cfg=new, avail=yes, need=no, active=unknown

```

**Comment by Wayonb** [comment]
This seems to an older processor which is currently not supported with our current build.
https://ark.intel.com/content/www/us/en/ark/products/47920/intel-xeon-processor-x5670-12m-cache-2-93-ghz-6-40-gt-s-intel-qpi.html

**Comment by gimer** [comment]
@dekm Officially, we don't support westmere architecture (it's too old), but if you really want there is an image that you might want to use:
`docker pull symbolplatform/symbol-server:gcc-1.0.0.0-westmere`
`docker pull symbolplatform/symbol-server:tools-gcc-1.0.0.0-westmere`

**Comment by fboucquez** [comment]
@dekm ,  I haven't tried those images, but if you want to use them you need to add this to your custom preset:

````
symbolServerToolsImage: symbolplatform/symbol-server:tools-gcc-1.0.0.0-westmere
symbolServerImage: symbolplatform/symbol-server:gcc-1.0.0.0-westmere
````
I'm closing this issue, let us know if you need further assistance
