### ISSUE TITLE
host disappears when I run config --upgrade on v1.0.1 mainnet

### ISSUE THREAD

**Issue by dusanjp** [nemtech/symbol-bootstrap#210]
With v1.0.1.
on mainnet
`symbol-bootstrap start -p mainnet -a dual --upgrade`
When you run
1. `config_node.properties`
2. `preset.yml`
The host name is removed from these two files

After noticing this
1. `config_node.properties`
2. `preset.yml`
After editing these two files, try again
`symbol-bootstrap start -p mainnet -a dual --upgrade`
When you run
Again the value of host is deleted

Even if you execute a similar instruction with testnet
This does not happen

This is happening across platforms
AMD RYZEN System
t4vps

**Comment by fboucquez** [comment]
is the hostname in (old) target/addresses.yml?

**Comment by dusanjp** [comment]
yes
I described `host / friendlyName` in my `customPreset.yml` and launched it.
After noticing this, I rewrote it in the target and tried again. It is the result of trying twice.
I will write it again, but even if I did the same thing as this, it did not occur with `-p testnet`

**Comment by dusanjp** [comment]
once again 
`config -p testnet -a dual --upgrade`
`config -p mainnet -a dual --upgrade`
I ran both and compared them. After all, the behavior is different.

**Comment by dusanjp** [comment]
Currently running "test8" on mainnet
IP address is 212.24.106.178

Currently host is missing in curl localhost: 3000 / node / info
Part of the contents of "test8" target / addresses.yml "
nodes:
     ---
         name: node
         friendlyName: test8
         roles:'Peer, Api'

**Comment by fboucquez** [comment]
Can you share your custom preset without any private information?

**Comment by dusanjp** [comment]
nodes:
    -
        host: 212.24.106.178
        friendlyName: test8
        maxUnlockedAccounts: 20

this is customPriset of "test8"

**Comment by dusanjp** [comment]
If you do not load customPreset, host seems to disappear.
On meinnet ...

**Comment by fboucquez** [comment]
Thanks @dusanjp , this has been fixed in the latest release
