### ISSUE TITLE
symbol-bootstrap@1.0.1  leave version = 1.0.0.0 in config-node.properties

### ISSUE THREAD

**Issue by kmn** [nemtech/symbol-bootstrap#216]
**Describe the bug**
version does not change even upgrade into v1.0.1

**To Reproduce**
To reproduce the behavior:
1. Write the full executed command or script
```
find ./target -type f -name "*properties"| xargs grep version
./target/nodes/node/server-config/resources/config-node.properties:version = 1.0.0.0
./target/nodes/node/broker-config/resources/config-node.properties:version = 1.0.0.0
./target/gateways/rest-gateway/api-node-config/config-node.properties:version = 1.0.0.0
```
2. Include the content of any custom preset file.

**Expected behavior**
```
./target/nodes/node/server-config/resources/config-node.properties:version = 1.0.1.0
./target/nodes/node/broker-config/resources/config-node.properties:version = 1.0.1.0
./target/gateways/rest-gateway/api-node-config/config-node.properties:version = 1.0.1.0
```

**Logs**
If applicable, add the full or partial logs to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. MacOs, Ubuntu]
 - Tool Version
 - Docker Version
 - Node Version

**Additional context**

**Comment by fboucquez** [comment]
1.0.1 and 1.0.2 are bootstrap patches, there is no server upgrade. The current official server is still 1.0.0.0
