### ISSUE TITLE
cannot read property 'current' of undefined ","jse_cause" : {} ...

### ISSUE THREAD

**Issue by ldh1428a** [nemtech/symbol-bootstrap#220]
**Describe the bug**
caught error 500 Cannot read property 'current' of undefined error.

**To Reproduce**
To reproduce the behavior:
symbol-bootstrap config -p mainnet -a dual
symbol-bootstrap compose
symbol-bootstrap run

**Expected behavior**
Just turn on dual mode at ubuntu 20.04.

**Logs**
error: caught error 500 Cannot read property 'current' of undefined {"jse_shortmsg":"Cannot read property 'current' of undefined","jse_cause":{},"jse_info":{},"body":{"code":"Internal","message":"Cannot read property 'current' of undefined"},"stack":"InternalError: Cannot read property 'current' of undefined\n    at Object.toRestError (/app/catapult-rest/rest/_build/server/errors.js:32:5)\n    at toRestError (/app/catapult-rest/rest/_build/server/bootstrapper.js:34:27)\n    at /app/catapult-rest/rest/_build/server/bootstrapper.js:163:13\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","timestamp":"2021-03-27T00:22:12.412Z"}

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04(x86_64)
 - Tool Version: symbol-bootstrap/1.0.2 linux-x64 node-v12.21.0
 - Docker Version: Docker version 20.10.5, build 55c4c88
 - Node Version: v12.21.0

**Comment by fboucquez** [comment]
In this case, the broker didn't run properly and the rest didn't have the full information in the mongo db. Do you see any errors above?

**Comment by ldh1428a** [comment]
Thanks reply, @fboucquez 

In this case, mongodb could not be started due to insufficient memory usage.

Up to 8 GB memory capacity, it worked !! 😄 😄 😄
