### ISSUE TITLE
Inconsistent case in properties

### ISSUE THREAD

**Issue by segfaultxavi** [nemtech/symbol-bootstrap#24]
In the `.yml` files (like [this one](https://github.com/nemtech/symbol-bootstrap/blob/main/presets/bootstrap/network.yml)) some properties use camelCase (like `friendlyName` and `enableSingleThreadPool`) whereas some others are all lowercase (like `addressextraction` and `filespooling`).
I understand some properties are defined in typescript and some others are defined in mustache, but whatever the reason, the different cases are confusing.

Are the property names case sensitive? What case should the documentation use?

**Comment by rg911** [comment]
They should all be camel case i guess @fboucquez ?

**Comment by fboucquez** [comment]
The names match the corresponding server properties that will be populateed. Some of them are lower case.

https://github.com/nemtech/symbol-bootstrap/blob/main/config/node/resources/config-extensions-recovery.properties.mustache#L4

Currently Symbol-bootstrap doesn't map all the properties. I guess we could use this ticket to revisit them. We may need to double check properties that are reused in different properties files and prefix them anyway.

**Comment by fboucquez** [comment]
Won't fix. Properties try to keep the naming of the target configuration file
