### ISSUE TITLE
The build 1.0.6-alpha-202105192112 is crashing

### ISSUE THREAD

**Issue by NikolaiB** [nemtech/symbol-bootstrap#253]
v. symbol-bootstrap/1.0.6-alpha-202105192112 linux-x64 node-v10.19.0

`ubuntu@ip-172-31-36-103:~$ docker logs rest-gateway

> catapult-api-rest@0.0.0 start /app/catapult-rest/rest
> node _build/index.js "/symbol-workdir/rest.json"

[winston] Attempt to write logs with no transports {"message":"loading config from /symbol-workdir/rest.json","level":"info"}
info: loading config from /symbol-workdir/rest.json
verbose: finished loading rest server config {"network":{"name":"publicTest","description":"catapult public test network"},"port":3000,"crossDomain":{"allowedHosts":["*"],"allowedMethods":["GET","POST","PUT","OPTIONS"]},"extensions":["accountLink","aggregate","lockHash","lockSecret","mosaic","metadata","multisig","namespace","receipts","restrictions","transfer","cmc"],"db":{"url":"mongodb://db:27017/","name":"catapult","pageSizeMin":10,"pageSizeMax":100,"maxConnectionAttempts":15,"baseRetryDelay":750,"connectionPoolSize":10},"apiNode":{"host":"node","port":7900,"tlsClientCertificatePath":"/symbol-workdir/api-node-config/cert/node.crt.pem","tlsClientKeyPath":"/symbol-workdir/api-node-config/cert/node.key.pem","tlsCaCertificatePath":"/symbol-workdir/api-node-config/cert/ca.cert.pem","timeout":1000,"networkPropertyFilePath":"/symbol-workdir/api-node-config/config-network.properties","nodePropertyFilePath":"/symbol-workdir/api-node-config/config-node.properties"},"websocket":{"mq":{"host":"broker","port":7902,"monitorInterval":500,"connectTimeout":10000,"monitorLoggingThrottle":60000,"maxSubscriptions":300},"allowOptionalAddress":true},"throttling":{"burst":80,"rate":60},"logging":{"console":{"formats":["colorize","simple"],"level":"verbose","handleExceptions":true},"file":{"formats":["prettyPrint"],"level":"verbose","handleExceptions":true,"filename":"/symbol-workdir/logs/catapult-rest.log","maxsize":20971520,"maxFiles":100}},"numBlocksTransactionFeeStats":300,"timestamp":"2021-05-21T08:53:36.418Z"}
info: connecting to mongodb://db:27017/ (database:catapult) {"timestamp":"2021-05-21T08:53:36.447Z"}
(node:18) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
warn: db connection failed, retrying in 750ms failed to connect to server [db:27017] on first connect [Error: connect ECONNREFUSED 172.20.0.3:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  name: 'MongoNetworkError'
}] {"name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [db:27017] on first connect [Error: connect ECONNREFUSED 172.20.0.3:27017\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {\n  name: 'MongoNetworkError'\n}]\n    at Pool.<anonymous> (/app/catapult-rest/rest/node_modules/mongodb/lib/core/topologies/server.js:438:11)\n    at Pool.emit (events.js:315:20)\n    at /app/catapult-rest/rest/node_modules/mongodb/lib/core/connection/pool.js:562:14\n    at /app/catapult-rest/rest/node_modules/mongodb/lib/core/connection/pool.js:995:11\n    at /app/catapult-rest/rest/node_modules/mongodb/lib/core/connection/connect.js:32:7\n    at callback (/app/catapult-rest/rest/node_modules/mongodb/lib/core/connection/connect.js:280:5)\n    at Socket.<anonymous> (/app/catapult-rest/rest/node_modules/mongodb/lib/core/connection/connect.js:310:7)\n    at Object.onceWrapper (events.js:422:26)\n    at Socket.emit (events.js:315:20)\n    at emitErrorNT (internal/streams/destroy.js:92:8)","timestamp":"2021-05-21T08:53:36.465Z"}
warn: db connection failed, retrying in 1500ms failed to connect to server [db:27017] on first connect [Error: connect ECONNREFUSED 172.20.0.3:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  name: 'MongoNetworkError'
}] {"name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [db:27017] on first connect [Error: connect ECONNREFUSED 172.20.0.3:27017\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {\n  name: 'MongoNetworkError'\n}]\n    at Pool.<anonymous> (/app/catapult-rest/rest/node_modules/mongodb/lib/core/topologies/server.js:438:11)\n    at Pool.emit (events.js:315:20)\n    at /app/catapult-rest/rest/node_modules/mongodb/lib/core/connection/pool.js:562:14\n    at /app/catapult-rest/rest/node_modules/mongodb/lib/core/connection/pool.js:995:11\n    at /app/catapult-rest/rest/node_modules/mongodb/lib/core/connection/connect.js:32:7\n    at callback (/app/catapult-rest/rest/node_modules/mongodb/lib/core/connection/connect.js:280:5)\n    at Socket.<anonymous> (/app/catapult-rest/rest/node_modules/mongodb/lib/core/connection/connect.js:310:7)\n    at Object.onceWrapper (events.js:422:26)\n    at Socket.emit (events.js:315:20)\n    at emitErrorNT (internal/streams/destroy.js:92:8)","timestamp":"2021-05-21T08:53:37.219Z"}
verbose: connected to mongo at mongodb://db:27017/catapult {"timestamp":"2021-05-21T08:53:38.729Z"}
info: registering routes {"timestamp":"2021-05-21T08:53:38.730Z"}
error: rest server is exiting due to error plugin 'cmc' not supported by model system {"stack":"Error: plugin 'cmc' not supported by model system\n    at /app/catapult-rest/catapult-sdk/_build/plugins/catapultModelSystem.js:77:11\n    at Array.forEach (<anonymous>)\n    at Object.configure (/app/catapult-rest/catapult-sdk/_build/plugins/catapultModelSystem.js:75:15)\n    at createServer (/app/catapult-rest/rest/_build/index.js:111:59)\n    at /app/catapult-rest/rest/_build/index.js:187:27\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","timestamp":"2021-05-21T08:53:38.733Z"}

> catapult-api-rest@0.0.0 start /app/catapult-rest/rest
> node _build/index.js "/symbol-workdir/rest.json"

[winston] Attempt to write logs with no transports {"message":"loading config from /symbol-workdir/rest.json","level":"info"}
info: loading config from /symbol-workdir/rest.json
verbose: finished loading rest server config {"network":{"name":"publicTest","description":"catapult public test network"},"port":3000,"crossDomain":{"allowedHosts":["*"],"allowedMethods":["GET","POST","PUT","OPTIONS"]},"extensions":["accountLink","aggregate","lockHash","lockSecret","mosaic","metadata","multisig","namespace","receipts","restrictions","transfer","cmc"],"db":{"url":"mongodb://db:27017/","name":"catapult","pageSizeMin":10,"pageSizeMax":100,"maxConnectionAttempts":15,"baseRetryDelay":750,"connectionPoolSize":10},"apiNode":{"host":"node","port":7900,"tlsClientCertificatePath":"/symbol-workdir/api-node-config/cert/node.crt.pem","tlsClientKeyPath":"/symbol-workdir/api-node-config/cert/node.key.pem","tlsCaCertificatePath":"/symbol-workdir/api-node-config/cert/ca.cert.pem","timeout":1000,"networkPropertyFilePath":"/symbol-workdir/api-node-config/config-network.properties","nodePropertyFilePath":"/symbol-workdir/api-node-config/config-node.properties"},"websocket":{"mq":{"host":"broker","port":7902,"monitorInterval":500,"connectTimeout":10000,"monitorLoggingThrottle":60000,"maxSubscriptions":300},"allowOptionalAddress":true},"throttling":{"burst":80,"rate":60},"logging":{"console":{"formats":["colorize","simple"],"level":"verbose","handleExceptions":true},"file":{"formats":["prettyPrint"],"level":"verbose","handleExceptions":true,"filename":"/symbol-workdir/logs/catapult-rest.log","maxsize":20971520,"maxFiles":100}},"numBlocksTransactionFeeStats":300,"timestamp":"2021-05-21T08:55:04.273Z"}
info: connecting to mongodb://db:27017/ (database:catapult) {"timestamp":"2021-05-21T08:55:04.295Z"}
(node:18) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
verbose: connected to mongo at mongodb://db:27017/catapult {"timestamp":"2021-05-21T08:55:04.315Z"}
info: registering routes {"timestamp":"2021-05-21T08:55:04.316Z"}
error: rest server is exiting due to error plugin 'cmc' not supported by model system {"stack":"Error: plugin 'cmc' not supported by model system\n    at /app/catapult-rest/catapult-sdk/_build/plugins/catapultModelSystem.js:77:11\n    at Array.forEach (<anonymous>)\n    at Object.configure (/app/catapult-rest/catapult-sdk/_build/plugins/catapultModelSystem.js:75:15)\n    at createServer (/app/catapult-rest/rest/_build/index.js:111:59)\n    at /app/catapult-rest/rest/_build/index.js:187:27\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","timestamp":"2021-05-21T08:55:04.320Z"}

> catapult-api-rest@0.0.0 start /app/catapult-rest/rest
> node _build/index.js "/symbol-workdir/rest.json"

[winston] Attempt to write logs with no transports {"message":"loading config from /symbol-workdir/rest.json","level":"info"}
info: loading config from /symbol-workdir/rest.json
verbose: finished loading rest server config {"network":{"name":"publicTest","description":"catapult public test network"},"port":3000,"crossDomain":{"allowedHosts":["*"],"allowedMethods":["GET","POST","PUT","OPTIONS"]},"extensions":["accountLink","aggregate","lockHash","lockSecret","mosaic","metadata","multisig","namespace","receipts","restrictions","transfer","cmc"],"db":{"url":"mongodb://db:27017/","name":"catapult","pageSizeMin":10,"pageSizeMax":100,"maxConnectionAttempts":15,"baseRetryDelay":750,"connectionPoolSize":10},"apiNode":{"host":"node","port":7900,"tlsClientCertificatePath":"/symbol-workdir/api-node-config/cert/node.crt.pem","tlsClientKeyPath":"/symbol-workdir/api-node-config/cert/node.key.pem","tlsCaCertificatePath":"/symbol-workdir/api-node-config/cert/ca.cert.pem","timeout":1000,"networkPropertyFilePath":"/symbol-workdir/api-node-config/config-network.properties","nodePropertyFilePath":"/symbol-workdir/api-node-config/config-node.properties"},"websocket":{"mq":{"host":"broker","port":7902,"monitorInterval":500,"connectTimeout":10000,"monitorLoggingThrottle":60000,"maxSubscriptions":300},"allowOptionalAddress":true},"throttling":{"burst":80,"rate":60},"logging":{"console":{"formats":["colorize","simple"],"level":"verbose","handleExceptions":true},"file":{"formats":["prettyPrint"],"level":"verbose","handleExceptions":true,"filename":"/symbol-workdir/logs/catapult-rest.log","maxsize":20971520,"maxFiles":100}},"numBlocksTransactionFeeStats":300,"timestamp":"2021-05-21T09:15:45.816Z"}
info: connecting to mongodb://db:27017/ (database:catapult) {"timestamp":"2021-05-21T09:15:45.838Z"}
(node:19) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
warn: db connection failed, retrying in 750ms failed to connect to server [db:27017] on first connect [Error: connect ECONNREFUSED 172.20.0.2:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  name: 'MongoNetworkError'
}] {"name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [db:27017] on first connect [Error: connect ECONNREFUSED 172.20.0.2:27017\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {\n  name: 'MongoNetworkError'\n}]\n    at Pool.<anonymous> (/app/catapult-rest/rest/node_modules/mongodb/lib/core/topologies/server.js:438:11)\n    at Pool.emit (events.js:315:20)\n    at /app/catapult-rest/rest/node_modules/mongodb/lib/core/connection/pool.js:562:14\n    at /app/catapult-rest/rest/node_modules/mongodb/lib/core/connection/pool.js:995:11\n    at /app/catapult-rest/rest/node_modules/mongodb/lib/core/connection/connect.js:32:7\n    at callback (/app/catapult-rest/rest/node_modules/mongodb/lib/core/connection/connect.js:280:5)\n    at Socket.<anonymous> (/app/catapult-rest/rest/node_modules/mongodb/lib/core/connection/connect.js:310:7)\n    at Object.onceWrapper (events.js:422:26)\n    at Socket.emit (events.js:315:20)\n    at emitErrorNT (internal/streams/destroy.js:92:8)","timestamp":"2021-05-21T09:15:45.856Z"}
warn: db connection failed, retrying in 1500ms failed to connect to server [db:27017] on first connect [Error: connect ECONNREFUSED 172.20.0.2:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  name: 'MongoNetworkError'
}] {"name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [db:27017] on first connect [Error: connect ECONNREFUSED 172.20.0.2:27017\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {\n  name: 'MongoNetworkError'\n}]\n    at Pool.<anonymous> (/app/catapult-rest/rest/node_modules/mongodb/lib/core/topologies/server.js:438:11)\n    at Pool.emit (events.js:315:20)\n    at /app/catapult-rest/rest/node_modules/mongodb/lib/core/connection/pool.js:562:14\n    at /app/catapult-rest/rest/node_modules/mongodb/lib/core/connection/pool.js:995:11\n    at /app/catapult-rest/rest/node_modules/mongodb/lib/core/connection/connect.js:32:7\n    at callback (/app/catapult-rest/rest/node_modules/mongodb/lib/core/connection/connect.js:280:5)\n    at Socket.<anonymous> (/app/catapult-rest/rest/node_modules/mongodb/lib/core/connection/connect.js:310:7)\n    at Object.onceWrapper (events.js:422:26)\n    at Socket.emit (events.js:315:20)\n    at emitErrorNT (internal/streams/destroy.js:92:8)","timestamp":"2021-05-21T09:15:46.612Z"}
verbose: connected to mongo at mongodb://db:27017/catapult {"timestamp":"2021-05-21T09:15:48.121Z"}
info: registering routes {"timestamp":"2021-05-21T09:15:48.122Z"}
error: rest server is exiting due to error plugin 'cmc' not supported by model system {"stack":"Error: plugin 'cmc' not supported by model system\n    at /app/catapult-rest/catapult-sdk/_build/plugins/catapultModelSystem.js:77:11\n    at Array.forEach (<anonymous>)\n    at Object.configure (/app/catapult-rest/catapult-sdk/_build/plugins/catapultModelSystem.js:75:15)\n    at createServer (/app/catapult-rest/rest/_build/index.js:111:59)\n    at /app/catapult-rest/rest/_build/index.js:187:27\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","timestamp":"2021-05-21T09:15:48.127Z"}`

**Comment by fboucquez** [comment]
It was a mismatch upgrade between different branches alphas.
