### ISSUE TITLE
Can't run on linux/arm64

### ISSUE THREAD

**Issue by dark9** [nemtech/symbol-bootstrap#275]
**Describe the bug**
Can't run on linux/arm64.

**To Reproduce**
symbol-bootstrap start

**Expected behavior**
Please add symbolplatform/symbol-server and symbolplatform/symbol-rest linux/arm64 images.

**Logs**
`standard_init_linux.go:228: exec user process caused: exec format error`

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Tool Version: symbol-bootstrap/1.0.6 linux-arm64
 - Docker Version: 20.10.2
 - Node Version: 16.3.0

**Comment by Wayonb** [comment]
We havent added ARM support yet.

**Comment by gimer** [comment]
to clarify: we don't have public docker images with arm builds, but it is possible to compile on arm64

**Comment by dark9** [comment]
Ok, I see.
Myself make private images on arm64.
