### ISSUE TITLE
Allow for the bootstrap to run without defined services

### ISSUE THREAD

**Issue by Vektrat** [nemtech/symbol-bootstrap#30]
Give the option to configure the preset without running a service instance, at least for REST though i guess this will be useful if/when explorer is put in as well, or for other core resources

**Comment by Vektrat** [comment]
put this on hold, i will give more details because it may be that the rest service is being started after all

**Comment by fboucquez** [comment]
@Vektrat , do you want to generate the service configuration and not run the service or you just don't want to generate anything related to service? I'm guessing you want to have rest gateway config and certificates generated but exclude rest from docker execution so you can run your own rest.

**Comment by Vektrat** [comment]
rest gateway config i don't mind much (doesnt make much sense to generate it i guess) of course it's always helpful to have,but i don't think it fits much in the project

certificates i need those generated yes, and i don't even strictly consider them part of the REST ecosystem (rather a part of api-node), so i think generating those is not out of scope anyway
