### ISSUE TITLE
symbol-bootasrap run /start　一回の命令では　起動しない事が多い件

### ISSUE THREAD

**Issue by dusanjp** [nemtech/symbol-bootstrap#34]
symbol-bootasrap run -d / start -d Cases that often do not start with a single command
"symbol-bootstrap start -d" or "symbol-bootstrap run -d" 
Does not start with a one-time command
It will start in the 4th time at most

**Comment by 44uk** [comment]
It seems that default timeout value is too short. 
https://github.com/nemtech/symbol-bootstrap/blob/e2bb4a10ce8c47ed71082833538e181e1e65d79a/src/service/RunService.ts#L21
The problem can be escaped running with `--timeout 600000` (for example 10min.)

**Comment by dusanjp** [comment]
I tried it with "--timeout 300000".
"symbol-bootstrap run(or start) -d --timeout 300000"
 It seems to start with one command.
I've tried it several times and it all seems to be successful
I can go with this! thanks

**Comment by fboucquez** [comment]
Fixed by increasing timeout.

**Comment by 44uk** [comment]
It seems to be good. thanks!
