### ISSUE TITLE
bootstrap should only copy configuration for enabled extensions 

### ISSUE THREAD

**Issue by Jaguar0625** [nemtech/symbol-bootstrap#56]
**Describe the bug**
Bootstrap is creating/copying configuration files for disabled extensions. 

**To Reproduce**
Use bootstrap to setup a testnet node.
Notice config-networkheight.properties is created even though networkheight extension is disabled.

**Expected behavior**
config-networkheight.properties is not copied because the extension it configures is disabled.

**Comment by fboucquez** [comment]
I didn't want to figure out the logic about which file to copy depending on the configuration flags. At the moment all the files are being generated although they may not be used. 
Is there any secondary effect? Or is the file just not used?
I'll improve the generation.

**Comment by fboucquez** [comment]
Fixe in next 0.3.0 version
