### ISSUE TITLE
Allow in place upgrade of the catapult server

### ISSUE THREAD

**Issue by Wayonb** [nemtech/symbol-bootstrap#57]
**Is your feature request related to a problem? Please describe.**
Currently, for each release of the catapult server, it seems like there is no easy way to upgrade to the latest server and config.
In the current upgrade process, each user will need to create a custom.yml to keep their current config.  
The -r option deletes your entire target folder so your data folder is also lost and you need to resync.

**Describe the solution you'd like**
Create a `symbol-bootstrap upgradeServer` which will apply the latest server config and update the docker-compose.yml with the latest server image.

**Comment by fboucquez** [comment]
--upgrade flag added to v 0.3.0
