### ISSUE TITLE
Is it possible to improve the problem of having to start the block height from the beginning every time bootstrap is updated?

### ISSUE THREAD

**Issue by dusanjp** [nemtech/symbol-bootstrap#63]
It takes too long to synchronize every time there is a bootstrap update.
You have to monitor if you can synchronize every time! !! !!

Isn't it possible to restart the block height from that point even if bootstrap is updated? ?? ?? ?? ??

**Comment by fboucquez** [comment]
Hi @dusanjp , 

We are planning to add an "upgrade" command/flag. This would tell bootstrap to regenerate the configuration and compose without removing the local data. 

Please follow https://github.com/nemtech/symbol-bootstrap/issues/57

Cheers
Fernando
