### ISSUE TITLE
[Bug] perset.yml is not created when reading is not finished

### ISSUE THREAD

**Issue by NikolaiB** [nemtech/symbol-bootstrap#81]
While I am running `npm run e2e` I am getting a few Errors like this:

`2020-12-02T11:10:49.407Z error [AUDIT_LOG]  Transaction 9586573 type 3 ignored. Multisign for destination could not be created: 9489C6500225CECB1CF3A4264D3CF93620DD5D64CDF7627441D7376B7B32E546. Payload: 2801000000000000359454C7756578BC75BE772BB8D22D32A2D8394AECCFEF19AFFC8136FC7D124B50C3723B391486EE93D7ECE6899E4EA73288B43436FBAA41C9A7C4ACE6CF56019489C6500225CECB1CF3A4264D3CF93620DD5D64CDF7627441D7376B7B32E546000000000168414100000000000000000100000000000000960F1420508807D3470E9B0741052C28F4AD481A469A1AEDF166330A7A86D061800000000000000080000000000000009489C6500225CECB1CF3A4264D3CF93620DD5D64CDF7627441D7376B7B32E5460000000001685541020203000000000068B95C6B8D48E225BD9A2D13C5503AB16FFFA73551FF50DC686CB231A6763C54FF3877AB0768CFEFD7548287C5DBF6C26867F5D8FCAF5C41EF0C0EE7A71C1CACF808DCECE7975060. Error: RangeError: Maximum call stack size exceeded`

**Comment by fboucquez** [comment]
@NikolaiB I think this is a catapult-opt-in bug, not a bootstrap bug.  The collection tool didn't finish correctly so bootstrap complains there was no preset.
