### ISSUE TITLE
Which docker image to use?

### ISSUE THREAD

**Issue by magick93** [nemtech/symbol-bootstrap#95]
Hello

Are the images on https://hub.docker.com/r/techbureau/catapult-server/tags the official Nem Symbol server images?

If yes, which one is recommended?

And does the image run as root?

Thanks

**Comment by Jaguar0625** [comment]
moved to symbol-bootstrap

**Comment by fboucquez** [comment]
Can you run 'docker run hello-world' without sudo?

https://github.com/nemtech/symbol-bootstrap#requirements

To create the image, have you tried this?

https://github.com/IoDLT/iodlt-symbol-server-docker/

**Comment by fboucquez** [comment]
Closing. Nothing to do
